TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += devtsx1820p.db
DATA += devtsx1820p.proto

#=======================================
include $(TOP)/configure/RULES
